### ISSUE TITLE
PolyKinded Equality

### ISSUE THREAD

**Issue by shangaslammi** [matt-noonan/gdp#5]
Would it break anything to allow all kinds for the parameters of the `Equality` type? This would allow equality proofs that use promoted data types or e.g. `Nat`s.

**Comment by matt-noonan** [comment]
I don't *think* there is any problem with this. Is it as simple as adding `{-# LANGUAGE PolyKinds #-}` in `Theory.Equality`, or are there other changes that would also be needed?
