### ISSUE TITLE
Kind of GetArg

### ISSUE THREAD

**Issue by shangaslammi** [matt-noonan/gdp#6]
Currently the `Argument` type class is defined as

    class Argument (f :: k1) (n :: k2) where
      type GetArg f n   :: k1
      type SetArg f n x :: k1

However, I don't immediately see why the argument kind needs to be same as the kind of `f`. Could this be changed to

    class Argument (f :: k1) (n :: k2) where
      type GetArg f n   :: k
      type SetArg f n x :: k1

**Comment by matt-noonan** [comment]
Yes, I believe you're right about this.
