### ISSUE TITLE
Should all propositions be wrapped in Proof?

### ISSUE THREAD

**Issue by brnzhg** [matt-noonan/gdp#8]
https://github.com/matt-noonan/gdp/blob/6e09928c2c2f5467e09dfc69310d6b67d6361422/src/Theory/Equality.hs#L87-L88

It seems like there was a change at some point to wrap all propositions in the Proof type, but `apply` and `substitute ` require `(x == x')` rather than `Proof (x == x')`. Was this just overlooked or am I misunderstanding?

**Comment by matt-noonan** [comment]
@brnzhg Just overlooked, I think. Thanks for catching this!

**Comment by matt-noonan** [comment]
Resolved by #9
